baseURL = "https://elegant-galileo-58a184.netlify.com/"
languageCode = "en-us"
title = "SIM DFW Playbook"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "green"